//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolcarDistributorsSalesClient
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesOrderList", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public partial class SalesOrderList : object
    {
        
        private System.Collections.Generic.List<PolcarDistributorsSalesClient.SalesOrderResponse> ListOfOrdersField;
        
        private string ErrorCodeField;
        
        private string ErrorInformationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<PolcarDistributorsSalesClient.SalesOrderResponse> ListOfOrders
        {
            get
            {
                return this.ListOfOrdersField;
            }
            set
            {
                this.ListOfOrdersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorInformation
        {
            get
            {
                return this.ErrorInformationField;
            }
            set
            {
                this.ErrorInformationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesOrderResponse", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public partial class SalesOrderResponse : object
    {
        
        private System.Collections.Generic.List<PolcarDistributorsSalesClient.SalesOrderItemResponse> OrderedItemsResponseField;
        
        private System.Collections.Generic.List<PolcarDistributorsSalesClient.SalesOrderAttributeResponse> AttributesField;
        
        private string CustomerOrderNumberField;
        
        private string PolcarOrderNumberField;
        
        private string OrderingPersonField;
        
        private string AdditionalNotesField;
        
        private string DocumentCodeField;
        
        private string LabelCodeField;
        
        private bool UseDefaultShippingAddressField;
        
        private string ShippingAddressCodeField;
        
        private string DistributorCodeField;
        
        private string CustomerNumberField;
        
        private System.DateTime ShipmentDateField;
        
        private string ErrorCodeField;
        
        private string ErrorInformationField;
        
        private PolcarDistributorsSalesClient.SalesOrderStatus OrderStatusField;
        
        private int OrderStatusIdField;
        
        private string OrderStatusNameField;
        
        private string OrderIDField;
        
        private System.Nullable<int> MaterialReleaseReceiptStateIdField;
        
        private string MaterialReleaseReceiptStateDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<PolcarDistributorsSalesClient.SalesOrderItemResponse> OrderedItemsResponse
        {
            get
            {
                return this.OrderedItemsResponseField;
            }
            set
            {
                this.OrderedItemsResponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Collections.Generic.List<PolcarDistributorsSalesClient.SalesOrderAttributeResponse> Attributes
        {
            get
            {
                return this.AttributesField;
            }
            set
            {
                this.AttributesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CustomerOrderNumber
        {
            get
            {
                return this.CustomerOrderNumberField;
            }
            set
            {
                this.CustomerOrderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PolcarOrderNumber
        {
            get
            {
                return this.PolcarOrderNumberField;
            }
            set
            {
                this.PolcarOrderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string OrderingPerson
        {
            get
            {
                return this.OrderingPersonField;
            }
            set
            {
                this.OrderingPersonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AdditionalNotes
        {
            get
            {
                return this.AdditionalNotesField;
            }
            set
            {
                this.AdditionalNotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string DocumentCode
        {
            get
            {
                return this.DocumentCodeField;
            }
            set
            {
                this.DocumentCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string LabelCode
        {
            get
            {
                return this.LabelCodeField;
            }
            set
            {
                this.LabelCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool UseDefaultShippingAddress
        {
            get
            {
                return this.UseDefaultShippingAddressField;
            }
            set
            {
                this.UseDefaultShippingAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ShippingAddressCode
        {
            get
            {
                return this.ShippingAddressCodeField;
            }
            set
            {
                this.ShippingAddressCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string DistributorCode
        {
            get
            {
                return this.DistributorCodeField;
            }
            set
            {
                this.DistributorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string CustomerNumber
        {
            get
            {
                return this.CustomerNumberField;
            }
            set
            {
                this.CustomerNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.DateTime ShipmentDate
        {
            get
            {
                return this.ShipmentDateField;
            }
            set
            {
                this.ShipmentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string ErrorInformation
        {
            get
            {
                return this.ErrorInformationField;
            }
            set
            {
                this.ErrorInformationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public PolcarDistributorsSalesClient.SalesOrderStatus OrderStatus
        {
            get
            {
                return this.OrderStatusField;
            }
            set
            {
                this.OrderStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public int OrderStatusId
        {
            get
            {
                return this.OrderStatusIdField;
            }
            set
            {
                this.OrderStatusIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string OrderStatusName
        {
            get
            {
                return this.OrderStatusNameField;
            }
            set
            {
                this.OrderStatusNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=18)]
        public string OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public System.Nullable<int> MaterialReleaseReceiptStateId
        {
            get
            {
                return this.MaterialReleaseReceiptStateIdField;
            }
            set
            {
                this.MaterialReleaseReceiptStateIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string MaterialReleaseReceiptStateDescription
        {
            get
            {
                return this.MaterialReleaseReceiptStateDescriptionField;
            }
            set
            {
                this.MaterialReleaseReceiptStateDescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesOrderItemResponse", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public partial class SalesOrderItemResponse : object
    {
        
        private string PolcarPartNumberField;
        
        private string CustomerPartNumberField;
        
        private int QuantityOrderedField;
        
        private int QuantityAvilableField;
        
        private int QuantityCompletedField;
        
        private PolcarDistributorsSalesClient.SalesOrderItemAvailabilityStatus AvailabilityStatusField;
        
        private string DistributorCurrencyField;
        
        private decimal DistributorPriceField;
        
        private decimal CustomerPriceField;
        
        private string CustomerCurrencyField;
        
        private decimal CustomerBasePriceField;
        
        private decimal CustomerDiscountField;
        
        private string BasketRowIdField;
        
        private int QuantityInBasketField;
        
        private int QuantityCollectedField;
        
        private int QuantityMissingField;
        
        private string MaterialReleaseReceiptStateDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PolcarPartNumber
        {
            get
            {
                return this.PolcarPartNumberField;
            }
            set
            {
                this.PolcarPartNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CustomerPartNumber
        {
            get
            {
                return this.CustomerPartNumberField;
            }
            set
            {
                this.CustomerPartNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int QuantityOrdered
        {
            get
            {
                return this.QuantityOrderedField;
            }
            set
            {
                this.QuantityOrderedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int QuantityAvilable
        {
            get
            {
                return this.QuantityAvilableField;
            }
            set
            {
                this.QuantityAvilableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int QuantityCompleted
        {
            get
            {
                return this.QuantityCompletedField;
            }
            set
            {
                this.QuantityCompletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public PolcarDistributorsSalesClient.SalesOrderItemAvailabilityStatus AvailabilityStatus
        {
            get
            {
                return this.AvailabilityStatusField;
            }
            set
            {
                this.AvailabilityStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string DistributorCurrency
        {
            get
            {
                return this.DistributorCurrencyField;
            }
            set
            {
                this.DistributorCurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal DistributorPrice
        {
            get
            {
                return this.DistributorPriceField;
            }
            set
            {
                this.DistributorPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal CustomerPrice
        {
            get
            {
                return this.CustomerPriceField;
            }
            set
            {
                this.CustomerPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CustomerCurrency
        {
            get
            {
                return this.CustomerCurrencyField;
            }
            set
            {
                this.CustomerCurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public decimal CustomerBasePrice
        {
            get
            {
                return this.CustomerBasePriceField;
            }
            set
            {
                this.CustomerBasePriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public decimal CustomerDiscount
        {
            get
            {
                return this.CustomerDiscountField;
            }
            set
            {
                this.CustomerDiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=12)]
        public string BasketRowId
        {
            get
            {
                return this.BasketRowIdField;
            }
            set
            {
                this.BasketRowIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int QuantityInBasket
        {
            get
            {
                return this.QuantityInBasketField;
            }
            set
            {
                this.QuantityInBasketField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public int QuantityCollected
        {
            get
            {
                return this.QuantityCollectedField;
            }
            set
            {
                this.QuantityCollectedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public int QuantityMissing
        {
            get
            {
                return this.QuantityMissingField;
            }
            set
            {
                this.QuantityMissingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string MaterialReleaseReceiptStateDescription
        {
            get
            {
                return this.MaterialReleaseReceiptStateDescriptionField;
            }
            set
            {
                this.MaterialReleaseReceiptStateDescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesOrderAttributeResponse", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public partial class SalesOrderAttributeResponse : object
    {
        
        private string OrderIdField;
        
        private string NameField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesOrderStatus", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public enum SalesOrderStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Placed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Preprocessed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitsConfirmation = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Confirmed = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CanceledEmptyOrder = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitsForTransfer = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitsForTransferToTheBasket = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Transfered = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransferedAndAddedToTheBasket = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Preprocessed_Split = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransferredToNemesisAndConfirmed = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransferredToNemesisAndCanceled = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitsForTransferToDistributor = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransferredToDistributor = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorOccurredWhileTransferToDistributor = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorOccurredWhileTransferToDistributor_TransferWasStoppedAndDistributorWasNotified = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllItemsIncludedToSupplierOrder = 20,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesOrderItemAvailabilityStatus", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public enum SalesOrderItemAvailabilityStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unavailable = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Available = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartyAvailable = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QuantityExceedsVisibility = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistributorOrderList", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public partial class DistributorOrderList : object
    {
        
        private System.Collections.Generic.List<PolcarDistributorsSalesClient.DistributorSalesOrderResponse> ListOfOrdersField;
        
        private string ErrorCodeField;
        
        private string ErrorInformationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<PolcarDistributorsSalesClient.DistributorSalesOrderResponse> ListOfOrders
        {
            get
            {
                return this.ListOfOrdersField;
            }
            set
            {
                this.ListOfOrdersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorInformation
        {
            get
            {
                return this.ErrorInformationField;
            }
            set
            {
                this.ErrorInformationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistributorSalesOrderResponse", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public partial class DistributorSalesOrderResponse : object
    {
        
        private System.Collections.Generic.List<PolcarDistributorsSalesClient.DistributorSalesOrderItemResponse> OrderedItemsResponseField;
        
        private System.Collections.Generic.List<PolcarDistributorsSalesClient.DistributorSalesOrderAttributeResponse> OrderAttributesField;
        
        private string PolcarOrderNumberField;
        
        private string CustomerOrderNumberField;
        
        private string AdditionalNotesField;
        
        private int OrderStatusIdField;
        
        private string OrderStatusNameField;
        
        private string OrderingPersonField;
        
        private string ShippingAddressCodeField;
        
        private string LabelCodeField;
        
        private System.DateTime ShipmentDateField;
        
        private string DistributorCodeField;
        
        private string CustomerNumberField;
        
        private string DocumentCodeField;
        
        private string OrderIDField;
        
        private System.DateTime EntryDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<PolcarDistributorsSalesClient.DistributorSalesOrderItemResponse> OrderedItemsResponse
        {
            get
            {
                return this.OrderedItemsResponseField;
            }
            set
            {
                this.OrderedItemsResponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Collections.Generic.List<PolcarDistributorsSalesClient.DistributorSalesOrderAttributeResponse> OrderAttributes
        {
            get
            {
                return this.OrderAttributesField;
            }
            set
            {
                this.OrderAttributesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PolcarOrderNumber
        {
            get
            {
                return this.PolcarOrderNumberField;
            }
            set
            {
                this.PolcarOrderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CustomerOrderNumber
        {
            get
            {
                return this.CustomerOrderNumberField;
            }
            set
            {
                this.CustomerOrderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AdditionalNotes
        {
            get
            {
                return this.AdditionalNotesField;
            }
            set
            {
                this.AdditionalNotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int OrderStatusId
        {
            get
            {
                return this.OrderStatusIdField;
            }
            set
            {
                this.OrderStatusIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string OrderStatusName
        {
            get
            {
                return this.OrderStatusNameField;
            }
            set
            {
                this.OrderStatusNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string OrderingPerson
        {
            get
            {
                return this.OrderingPersonField;
            }
            set
            {
                this.OrderingPersonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ShippingAddressCode
        {
            get
            {
                return this.ShippingAddressCodeField;
            }
            set
            {
                this.ShippingAddressCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string LabelCode
        {
            get
            {
                return this.LabelCodeField;
            }
            set
            {
                this.LabelCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime ShipmentDate
        {
            get
            {
                return this.ShipmentDateField;
            }
            set
            {
                this.ShipmentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string DistributorCode
        {
            get
            {
                return this.DistributorCodeField;
            }
            set
            {
                this.DistributorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string CustomerNumber
        {
            get
            {
                return this.CustomerNumberField;
            }
            set
            {
                this.CustomerNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string DocumentCode
        {
            get
            {
                return this.DocumentCodeField;
            }
            set
            {
                this.DocumentCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=14)]
        public string OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.DateTime EntryDate
        {
            get
            {
                return this.EntryDateField;
            }
            set
            {
                this.EntryDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistributorSalesOrderItemResponse", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public partial class DistributorSalesOrderItemResponse : object
    {
        
        private string OrderIdField;
        
        private string PartNumberField;
        
        private int QuantityOrderedField;
        
        private int QuantityAvailableField;
        
        private int QuantityCompletedField;
        
        private string NotesField;
        
        private decimal PriceField;
        
        private string CurrencySymbolField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PartNumber
        {
            get
            {
                return this.PartNumberField;
            }
            set
            {
                this.PartNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int QuantityOrdered
        {
            get
            {
                return this.QuantityOrderedField;
            }
            set
            {
                this.QuantityOrderedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int QuantityAvailable
        {
            get
            {
                return this.QuantityAvailableField;
            }
            set
            {
                this.QuantityAvailableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int QuantityCompleted
        {
            get
            {
                return this.QuantityCompletedField;
            }
            set
            {
                this.QuantityCompletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CurrencySymbol
        {
            get
            {
                return this.CurrencySymbolField;
            }
            set
            {
                this.CurrencySymbolField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistributorSalesOrderAttributeResponse", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public partial class DistributorSalesOrderAttributeResponse : object
    {
        
        private string OrderIdField;
        
        private string NameField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales", ConfigurationName="PolcarDistributorsSalesClient.DistributorsSalesServiceSoap")]
    public interface DistributorsSalesServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales/GetListOfOrder" +
            "s", ReplyAction="*")]
        System.Threading.Tasks.Task<PolcarDistributorsSalesClient.GetListOfOrdersResponse> GetListOfOrdersAsync(PolcarDistributorsSalesClient.GetListOfOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales/GetListOfOrder" +
            "sV2", ReplyAction="*")]
        System.Threading.Tasks.Task<PolcarDistributorsSalesClient.GetListOfOrdersV2Response> GetListOfOrdersV2Async(PolcarDistributorsSalesClient.GetListOfOrdersV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales/GetListOfOrder" +
            "sV3", ReplyAction="*")]
        System.Threading.Tasks.Task<PolcarDistributorsSalesClient.GetListOfOrdersV3Response> GetListOfOrdersV3Async(PolcarDistributorsSalesClient.GetListOfOrdersV3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales/CancelOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<PolcarDistributorsSalesClient.CancelOrderResponse> CancelOrderAsync(PolcarDistributorsSalesClient.CancelOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales/CloseOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<PolcarDistributorsSalesClient.CloseOrderResponse> CloseOrderAsync(PolcarDistributorsSalesClient.CloseOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales/GetOrderDetail" +
            "s", ReplyAction="*")]
        System.Threading.Tasks.Task<PolcarDistributorsSalesClient.GetOrderDetailsResponse> GetOrderDetailsAsync(PolcarDistributorsSalesClient.GetOrderDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListOfOrdersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListOfOrders", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales", Order=0)]
        public PolcarDistributorsSalesClient.GetListOfOrdersRequestBody Body;
        
        public GetListOfOrdersRequest()
        {
        }
        
        public GetListOfOrdersRequest(PolcarDistributorsSalesClient.GetListOfOrdersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public partial class GetListOfOrdersRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DistributorCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool GetOpenOrdersOnly;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int BranchID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime DateFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime DateTo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool GetOrdersHeadersOnly;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int LanguageID;
        
        public GetListOfOrdersRequestBody()
        {
        }
        
        public GetListOfOrdersRequestBody(string DistributorCode, bool GetOpenOrdersOnly, int BranchID, System.DateTime DateFrom, System.DateTime DateTo, bool GetOrdersHeadersOnly, string Login, string Password, int LanguageID)
        {
            this.DistributorCode = DistributorCode;
            this.GetOpenOrdersOnly = GetOpenOrdersOnly;
            this.BranchID = BranchID;
            this.DateFrom = DateFrom;
            this.DateTo = DateTo;
            this.GetOrdersHeadersOnly = GetOrdersHeadersOnly;
            this.Login = Login;
            this.Password = Password;
            this.LanguageID = LanguageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListOfOrdersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListOfOrdersResponse", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales", Order=0)]
        public PolcarDistributorsSalesClient.GetListOfOrdersResponseBody Body;
        
        public GetListOfOrdersResponse()
        {
        }
        
        public GetListOfOrdersResponse(PolcarDistributorsSalesClient.GetListOfOrdersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public partial class GetListOfOrdersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PolcarDistributorsSalesClient.SalesOrderList GetListOfOrdersResult;
        
        public GetListOfOrdersResponseBody()
        {
        }
        
        public GetListOfOrdersResponseBody(PolcarDistributorsSalesClient.SalesOrderList GetListOfOrdersResult)
        {
            this.GetListOfOrdersResult = GetListOfOrdersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListOfOrdersV2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListOfOrdersV2", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales", Order=0)]
        public PolcarDistributorsSalesClient.GetListOfOrdersV2RequestBody Body;
        
        public GetListOfOrdersV2Request()
        {
        }
        
        public GetListOfOrdersV2Request(PolcarDistributorsSalesClient.GetListOfOrdersV2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public partial class GetListOfOrdersV2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string distributorCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool getOpenOrdersOnly;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int branchId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dateFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime dateTo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool getOrdersHeadersOnly;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int languageId;
        
        public GetListOfOrdersV2RequestBody()
        {
        }
        
        public GetListOfOrdersV2RequestBody(string distributorCode, bool getOpenOrdersOnly, int branchId, System.DateTime dateFrom, System.DateTime dateTo, bool getOrdersHeadersOnly, string login, string password, int languageId)
        {
            this.distributorCode = distributorCode;
            this.getOpenOrdersOnly = getOpenOrdersOnly;
            this.branchId = branchId;
            this.dateFrom = dateFrom;
            this.dateTo = dateTo;
            this.getOrdersHeadersOnly = getOrdersHeadersOnly;
            this.login = login;
            this.password = password;
            this.languageId = languageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListOfOrdersV2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListOfOrdersV2Response", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales", Order=0)]
        public PolcarDistributorsSalesClient.GetListOfOrdersV2ResponseBody Body;
        
        public GetListOfOrdersV2Response()
        {
        }
        
        public GetListOfOrdersV2Response(PolcarDistributorsSalesClient.GetListOfOrdersV2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public partial class GetListOfOrdersV2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PolcarDistributorsSalesClient.DistributorOrderList GetListOfOrdersV2Result;
        
        public GetListOfOrdersV2ResponseBody()
        {
        }
        
        public GetListOfOrdersV2ResponseBody(PolcarDistributorsSalesClient.DistributorOrderList GetListOfOrdersV2Result)
        {
            this.GetListOfOrdersV2Result = GetListOfOrdersV2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListOfOrdersV3Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListOfOrdersV3", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales", Order=0)]
        public PolcarDistributorsSalesClient.GetListOfOrdersV3RequestBody Body;
        
        public GetListOfOrdersV3Request()
        {
        }
        
        public GetListOfOrdersV3Request(PolcarDistributorsSalesClient.GetListOfOrdersV3RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public partial class GetListOfOrdersV3RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string distributorCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool getOpenOrdersOnly;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int branchId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dateFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime dateTo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool getOrdersHeadersOnly;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int languageId;
        
        public GetListOfOrdersV3RequestBody()
        {
        }
        
        public GetListOfOrdersV3RequestBody(string distributorCode, bool getOpenOrdersOnly, int branchId, System.DateTime dateFrom, System.DateTime dateTo, bool getOrdersHeadersOnly, string login, string password, int languageId)
        {
            this.distributorCode = distributorCode;
            this.getOpenOrdersOnly = getOpenOrdersOnly;
            this.branchId = branchId;
            this.dateFrom = dateFrom;
            this.dateTo = dateTo;
            this.getOrdersHeadersOnly = getOrdersHeadersOnly;
            this.login = login;
            this.password = password;
            this.languageId = languageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListOfOrdersV3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListOfOrdersV3Response", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales", Order=0)]
        public PolcarDistributorsSalesClient.GetListOfOrdersV3ResponseBody Body;
        
        public GetListOfOrdersV3Response()
        {
        }
        
        public GetListOfOrdersV3Response(PolcarDistributorsSalesClient.GetListOfOrdersV3ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public partial class GetListOfOrdersV3ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PolcarDistributorsSalesClient.DistributorOrderList GetListOfOrdersV3Result;
        
        public GetListOfOrdersV3ResponseBody()
        {
        }
        
        public GetListOfOrdersV3ResponseBody(PolcarDistributorsSalesClient.DistributorOrderList GetListOfOrdersV3Result)
        {
            this.GetListOfOrdersV3Result = GetListOfOrdersV3Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelOrder", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales", Order=0)]
        public PolcarDistributorsSalesClient.CancelOrderRequestBody Body;
        
        public CancelOrderRequest()
        {
        }
        
        public CancelOrderRequest(PolcarDistributorsSalesClient.CancelOrderRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public partial class CancelOrderRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DistributorCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OrderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int LanguageID;
        
        public CancelOrderRequestBody()
        {
        }
        
        public CancelOrderRequestBody(string DistributorCode, string OrderID, string Login, string Password, int LanguageID)
        {
            this.DistributorCode = DistributorCode;
            this.OrderID = OrderID;
            this.Login = Login;
            this.Password = Password;
            this.LanguageID = LanguageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelOrderResponse", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales", Order=0)]
        public PolcarDistributorsSalesClient.CancelOrderResponseBody Body;
        
        public CancelOrderResponse()
        {
        }
        
        public CancelOrderResponse(PolcarDistributorsSalesClient.CancelOrderResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public partial class CancelOrderResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PolcarDistributorsSalesClient.SalesOrderResponse CancelOrderResult;
        
        public CancelOrderResponseBody()
        {
        }
        
        public CancelOrderResponseBody(PolcarDistributorsSalesClient.SalesOrderResponse CancelOrderResult)
        {
            this.CancelOrderResult = CancelOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CloseOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CloseOrder", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales", Order=0)]
        public PolcarDistributorsSalesClient.CloseOrderRequestBody Body;
        
        public CloseOrderRequest()
        {
        }
        
        public CloseOrderRequest(PolcarDistributorsSalesClient.CloseOrderRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public partial class CloseOrderRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DistributorCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OrderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int LanguageID;
        
        public CloseOrderRequestBody()
        {
        }
        
        public CloseOrderRequestBody(string DistributorCode, string OrderID, string Login, string Password, int LanguageID)
        {
            this.DistributorCode = DistributorCode;
            this.OrderID = OrderID;
            this.Login = Login;
            this.Password = Password;
            this.LanguageID = LanguageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CloseOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CloseOrderResponse", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales", Order=0)]
        public PolcarDistributorsSalesClient.CloseOrderResponseBody Body;
        
        public CloseOrderResponse()
        {
        }
        
        public CloseOrderResponse(PolcarDistributorsSalesClient.CloseOrderResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public partial class CloseOrderResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PolcarDistributorsSalesClient.SalesOrderResponse CloseOrderResult;
        
        public CloseOrderResponseBody()
        {
        }
        
        public CloseOrderResponseBody(PolcarDistributorsSalesClient.SalesOrderResponse CloseOrderResult)
        {
            this.CloseOrderResult = CloseOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderDetailsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderDetails", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales", Order=0)]
        public PolcarDistributorsSalesClient.GetOrderDetailsRequestBody Body;
        
        public GetOrderDetailsRequest()
        {
        }
        
        public GetOrderDetailsRequest(PolcarDistributorsSalesClient.GetOrderDetailsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public partial class GetOrderDetailsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DistributorCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OrderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int LanguageID;
        
        public GetOrderDetailsRequestBody()
        {
        }
        
        public GetOrderDetailsRequestBody(string DistributorCode, string OrderID, string Login, string Password, int LanguageID)
        {
            this.DistributorCode = DistributorCode;
            this.OrderID = OrderID;
            this.Login = Login;
            this.Password = Password;
            this.LanguageID = LanguageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderDetailsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderDetailsResponse", Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales", Order=0)]
        public PolcarDistributorsSalesClient.GetOrderDetailsResponseBody Body;
        
        public GetOrderDetailsResponse()
        {
        }
        
        public GetOrderDetailsResponse(PolcarDistributorsSalesClient.GetOrderDetailsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com/Integration/WebServices/Distributors/Sales")]
    public partial class GetOrderDetailsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PolcarDistributorsSalesClient.SalesOrderResponse GetOrderDetailsResult;
        
        public GetOrderDetailsResponseBody()
        {
        }
        
        public GetOrderDetailsResponseBody(PolcarDistributorsSalesClient.SalesOrderResponse GetOrderDetailsResult)
        {
            this.GetOrderDetailsResult = GetOrderDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface DistributorsSalesServiceSoapChannel : PolcarDistributorsSalesClient.DistributorsSalesServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class DistributorsSalesServiceSoapClient : System.ServiceModel.ClientBase<PolcarDistributorsSalesClient.DistributorsSalesServiceSoap>, PolcarDistributorsSalesClient.DistributorsSalesServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DistributorsSalesServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(DistributorsSalesServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), DistributorsSalesServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DistributorsSalesServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DistributorsSalesServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DistributorsSalesServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DistributorsSalesServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DistributorsSalesServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolcarDistributorsSalesClient.GetListOfOrdersResponse> PolcarDistributorsSalesClient.DistributorsSalesServiceSoap.GetListOfOrdersAsync(PolcarDistributorsSalesClient.GetListOfOrdersRequest request)
        {
            return base.Channel.GetListOfOrdersAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolcarDistributorsSalesClient.GetListOfOrdersResponse> GetListOfOrdersAsync(string DistributorCode, bool GetOpenOrdersOnly, int BranchID, System.DateTime DateFrom, System.DateTime DateTo, bool GetOrdersHeadersOnly, string Login, string Password, int LanguageID)
        {
            PolcarDistributorsSalesClient.GetListOfOrdersRequest inValue = new PolcarDistributorsSalesClient.GetListOfOrdersRequest();
            inValue.Body = new PolcarDistributorsSalesClient.GetListOfOrdersRequestBody();
            inValue.Body.DistributorCode = DistributorCode;
            inValue.Body.GetOpenOrdersOnly = GetOpenOrdersOnly;
            inValue.Body.BranchID = BranchID;
            inValue.Body.DateFrom = DateFrom;
            inValue.Body.DateTo = DateTo;
            inValue.Body.GetOrdersHeadersOnly = GetOrdersHeadersOnly;
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.LanguageID = LanguageID;
            return ((PolcarDistributorsSalesClient.DistributorsSalesServiceSoap)(this)).GetListOfOrdersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolcarDistributorsSalesClient.GetListOfOrdersV2Response> PolcarDistributorsSalesClient.DistributorsSalesServiceSoap.GetListOfOrdersV2Async(PolcarDistributorsSalesClient.GetListOfOrdersV2Request request)
        {
            return base.Channel.GetListOfOrdersV2Async(request);
        }
        
        public System.Threading.Tasks.Task<PolcarDistributorsSalesClient.GetListOfOrdersV2Response> GetListOfOrdersV2Async(string distributorCode, bool getOpenOrdersOnly, int branchId, System.DateTime dateFrom, System.DateTime dateTo, bool getOrdersHeadersOnly, string login, string password, int languageId)
        {
            PolcarDistributorsSalesClient.GetListOfOrdersV2Request inValue = new PolcarDistributorsSalesClient.GetListOfOrdersV2Request();
            inValue.Body = new PolcarDistributorsSalesClient.GetListOfOrdersV2RequestBody();
            inValue.Body.distributorCode = distributorCode;
            inValue.Body.getOpenOrdersOnly = getOpenOrdersOnly;
            inValue.Body.branchId = branchId;
            inValue.Body.dateFrom = dateFrom;
            inValue.Body.dateTo = dateTo;
            inValue.Body.getOrdersHeadersOnly = getOrdersHeadersOnly;
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.languageId = languageId;
            return ((PolcarDistributorsSalesClient.DistributorsSalesServiceSoap)(this)).GetListOfOrdersV2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolcarDistributorsSalesClient.GetListOfOrdersV3Response> PolcarDistributorsSalesClient.DistributorsSalesServiceSoap.GetListOfOrdersV3Async(PolcarDistributorsSalesClient.GetListOfOrdersV3Request request)
        {
            return base.Channel.GetListOfOrdersV3Async(request);
        }
        
        public System.Threading.Tasks.Task<PolcarDistributorsSalesClient.GetListOfOrdersV3Response> GetListOfOrdersV3Async(string distributorCode, bool getOpenOrdersOnly, int branchId, System.DateTime dateFrom, System.DateTime dateTo, bool getOrdersHeadersOnly, string login, string password, int languageId)
        {
            PolcarDistributorsSalesClient.GetListOfOrdersV3Request inValue = new PolcarDistributorsSalesClient.GetListOfOrdersV3Request();
            inValue.Body = new PolcarDistributorsSalesClient.GetListOfOrdersV3RequestBody();
            inValue.Body.distributorCode = distributorCode;
            inValue.Body.getOpenOrdersOnly = getOpenOrdersOnly;
            inValue.Body.branchId = branchId;
            inValue.Body.dateFrom = dateFrom;
            inValue.Body.dateTo = dateTo;
            inValue.Body.getOrdersHeadersOnly = getOrdersHeadersOnly;
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.languageId = languageId;
            return ((PolcarDistributorsSalesClient.DistributorsSalesServiceSoap)(this)).GetListOfOrdersV3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolcarDistributorsSalesClient.CancelOrderResponse> PolcarDistributorsSalesClient.DistributorsSalesServiceSoap.CancelOrderAsync(PolcarDistributorsSalesClient.CancelOrderRequest request)
        {
            return base.Channel.CancelOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolcarDistributorsSalesClient.CancelOrderResponse> CancelOrderAsync(string DistributorCode, string OrderID, string Login, string Password, int LanguageID)
        {
            PolcarDistributorsSalesClient.CancelOrderRequest inValue = new PolcarDistributorsSalesClient.CancelOrderRequest();
            inValue.Body = new PolcarDistributorsSalesClient.CancelOrderRequestBody();
            inValue.Body.DistributorCode = DistributorCode;
            inValue.Body.OrderID = OrderID;
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.LanguageID = LanguageID;
            return ((PolcarDistributorsSalesClient.DistributorsSalesServiceSoap)(this)).CancelOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolcarDistributorsSalesClient.CloseOrderResponse> PolcarDistributorsSalesClient.DistributorsSalesServiceSoap.CloseOrderAsync(PolcarDistributorsSalesClient.CloseOrderRequest request)
        {
            return base.Channel.CloseOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolcarDistributorsSalesClient.CloseOrderResponse> CloseOrderAsync(string DistributorCode, string OrderID, string Login, string Password, int LanguageID)
        {
            PolcarDistributorsSalesClient.CloseOrderRequest inValue = new PolcarDistributorsSalesClient.CloseOrderRequest();
            inValue.Body = new PolcarDistributorsSalesClient.CloseOrderRequestBody();
            inValue.Body.DistributorCode = DistributorCode;
            inValue.Body.OrderID = OrderID;
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.LanguageID = LanguageID;
            return ((PolcarDistributorsSalesClient.DistributorsSalesServiceSoap)(this)).CloseOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolcarDistributorsSalesClient.GetOrderDetailsResponse> PolcarDistributorsSalesClient.DistributorsSalesServiceSoap.GetOrderDetailsAsync(PolcarDistributorsSalesClient.GetOrderDetailsRequest request)
        {
            return base.Channel.GetOrderDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolcarDistributorsSalesClient.GetOrderDetailsResponse> GetOrderDetailsAsync(string DistributorCode, string OrderID, string Login, string Password, int LanguageID)
        {
            PolcarDistributorsSalesClient.GetOrderDetailsRequest inValue = new PolcarDistributorsSalesClient.GetOrderDetailsRequest();
            inValue.Body = new PolcarDistributorsSalesClient.GetOrderDetailsRequestBody();
            inValue.Body.DistributorCode = DistributorCode;
            inValue.Body.OrderID = OrderID;
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.LanguageID = LanguageID;
            return ((PolcarDistributorsSalesClient.DistributorsSalesServiceSoap)(this)).GetOrderDetailsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DistributorsSalesServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.DistributorsSalesServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DistributorsSalesServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://dedal.polcar.com:8080/Sales/DistributorsSalesService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.DistributorsSalesServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://dedal.polcar.com:8080/Sales/DistributorsSalesService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            DistributorsSalesServiceSoap,
            
            DistributorsSalesServiceSoap12,
        }
    }
}
