openapi: 3.0.1
info:
  title: 'Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
  version: '1.0'
paths:
  /api/Orders:
    get:
      tags:
        - Orders
      operationId: GetOrders
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderDto'
  /api/settings/ifirmaSettings:
    get:
      tags:
        - settings/ifirmaSettings
      operationId: GetIFirmaSettings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IFirmaSettingDto'
    post:
      tags:
        - settings/ifirmaSettings
      operationId: CreateIFirmaSetting
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateIFirmaSettingCommand'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: integer
                format: int32
  '/api/settings/ifirmaSettings/{id}':
    get:
      tags:
        - settings/ifirmaSettings
      operationId: GetIFirmaSetting
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IFirmaSettingDto'
    delete:
      tags:
        - settings/ifirmaSettings
      operationId: DeleteIFirmaSetting
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
  /api/settings/mongodbSettings:
    get:
      tags:
        - settings/mongodbSettings
      operationId: GetMongoDBSettings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MongoDBSettingDto'
    post:
      tags:
        - settings/mongodbSettings
      operationId: CreateMongoDBSetting
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMongoDBSettingCommand'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: integer
                format: int32
  '/api/settings/mongodbSettings/{id}':
    get:
      tags:
        - settings/mongodbSettings
      operationId: GetMongoDBSetting
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MongoDBSettingDto'
    delete:
      tags:
        - settings/mongodbSettings
      operationId: DeleteMongoDBSetting
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
  /api/settings/polcarSettings:
    get:
      tags:
        - settings/polcarSettings
      operationId: GetPolcarSettings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PolcarSettingDto'
    post:
      tags:
        - settings/polcarSettings
      operationId: CreatePolcarSetting
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePolcarSettingCommand'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: integer
                format: int32
  '/api/settings/polcarSettings/{id}':
    get:
      tags:
        - settings/polcarSettings
      operationId: GetPolcarSetting
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolcarSettingDto'
    delete:
      tags:
        - settings/polcarSettings
      operationId: DeletePolcarSetting
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
  /api/settings/userSettings:
    get:
      tags:
        - settings/userSettings
      operationId: GetUserSettings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserSettingDto'
    post:
      tags:
        - settings/userSettings
      operationId: CreateUserSetting
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserSettingCommand'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: integer
                format: int32
  '/api/settings/userSettings/{id}':
    get:
      tags:
        - settings/userSettings
      operationId: GetUserSetting
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSettingDto'
    delete:
      tags:
        - settings/userSettings
      operationId: DeleteUserSetting
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
components:
  schemas:
    CreateIFirmaSettingCommand:
      required:
        - email
        - fakturaApiKey
      type: object
      properties:
        email:
          minLength: 1
          type: string
        fakturaApiKey:
          minLength: 1
          type: string
      additionalProperties: false
    CreateMongoDBSettingCommand:
      required:
        - collectionName
        - connectionURI
        - databaseName
      type: object
      properties:
        connectionURI:
          minLength: 1
          type: string
        databaseName:
          minLength: 1
          type: string
        collectionName:
          minLength: 1
          type: string
      additionalProperties: false
    CreatePolcarSettingCommand:
      required:
        - branchId
        - distributorCode
        - languageId
        - login
        - password
      type: object
      properties:
        login:
          minLength: 1
          type: string
        password:
          minLength: 1
          type: string
        distributorCode:
          minLength: 1
          type: string
        branchId:
          type: integer
          format: int32
        languageId:
          type: integer
          format: int32
      additionalProperties: false
    CreateUserSettingCommand:
      required:
        - auth0Id
        - iFirmaSettingId
        - mongoDBSettingId
        - polcarSettingId
      type: object
      properties:
        auth0Id:
          minLength: 1
          type: string
        iFirmaSettingId:
          type: integer
          format: int32
        polcarSettingId:
          type: integer
          format: int32
        mongoDBSettingId:
          type: integer
          format: int32
      additionalProperties: false
    IFirmaSettingDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        email:
          type: string
          nullable: true
        fakturaApiKey:
          type: string
          nullable: true
      additionalProperties: false
    MongoDBSettingDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        connectionURI:
          type: string
          nullable: true
        databaseName:
          type: string
          nullable: true
        collectionName:
          type: string
          nullable: true
      additionalProperties: false
    OrderDto:
      type: object
      additionalProperties: false
    PolcarSettingDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        login:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
        distributorCode:
          type: string
          nullable: true
        branchId:
          type: integer
          format: int32
        languageId:
          type: integer
          format: int32
      additionalProperties: false
    UserSettingDto:
      type: object
      properties:
        email:
          type: string
          nullable: true
        fakturaEmail:
          type: string
          nullable: true
        distributorCode:
          type: string
          nullable: true
        branchId:
          type: integer
          format: int32
        languageId:
          type: integer
          format: int32
        databaseName:
          type: string
          nullable: true
        collectionName:
          type: string
          nullable: true
      additionalProperties: false